<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<AzureFunctionsVersion>v4</AzureFunctionsVersion>
		<Platforms>x64</Platforms>
		<!-- <RootNamespace>contoso_functionsapp</RootNamespace> -->
	</PropertyGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="Azure.Messaging.ServiceBus" Version="7.19.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
		<!-- Application Insights isn't enabled by default. See https://aka.ms/AAt8mw4. -->
		<!-- <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" /> -->
		<!-- <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="2.0.0" /> -->
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.2.3" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.3.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="2.0.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
		<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.6.0" />
		<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="3.0.4" />
		<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="5.16.6" />
		<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.3.4" />
		<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi" Version="1.5.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
		<PackageReference Include="System.Memory.Data" Version="8.0.1" />
	</ItemGroup>
	<ItemGroup>
		<None Update="host.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="local.settings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
		<FunctionsPreservedDependencies Include="System.Memory.Data.dll" />
	</ItemGroup>
	<ItemGroup>
		<Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="../Contoso.Infrastructure.Messaging/Contoso.Infrastructure.Messaging.csproj" />
		<ProjectReference Include="..\Contoso.Infrastructure.Context\Contoso.Infrastructure.Context.csproj">
			<GlobalPropertiesToRemove></GlobalPropertiesToRemove>
		</ProjectReference>
		<ProjectReference Include="..\Contoso.Infrastructure.Core\Contoso.Infrastructure.Core.csproj">
			<GlobalPropertiesToRemove></GlobalPropertiesToRemove>
		</ProjectReference>
		<ProjectReference Include="..\Contoso.Utilities.Logging\Contoso.Utilities.Logging.csproj">
			<GlobalPropertiesToRemove></GlobalPropertiesToRemove>
		</ProjectReference>
	</ItemGroup>
</Project>